# Generated by Django 3.2.9 on 2021-11-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
